### ISSUE TITLE
Unable to install better-sqlite3

### ISSUE THREAD

**Issue by rvenkatraman02** [comp426-2022-spring/a04#4]
Whenever I try to run the command 'npm install better-sqlite3' in my terminal I get a series of errors and I am not sure how to fix it.

![image](https://user-images.githubusercontent.com/77650452/160457118-0a22d90e-1da3-4fa1-a65b-2cedde772143.png)

**Comment by mbrightman** [comment]
![image](https://user-images.githubusercontent.com/45112220/160646877-7b6d8265-0a71-4dab-aba4-cac3e5e70979.png)

I am having a similar issue using the same command in VS Code.

**Comment by mbrightman** [comment]
UPDATE: I was working on trying to remedy my error and I have - I am now getting the same error as @rvenkatraman02

**Comment by jdmar3** [comment]
So, this is a silly-sounding thing, but I notice that in both of the examples y'all give above, there is a space somewhere in the path that you are using as your install target. @rvenkatraman02, your path has `...\Spring 2022\COMP 426\...` and @mbrightman, your path has `...\SCHOOL WORK\...`

I have definitely seen Node choke on spaces in paths in weird ways before, so I might recommend replacing the spaces in with underscores or just removing them altogether and seeing if that helps.

**Comment by jdmar3** [comment]
Okay, so that doesn't appear to be it.

**Comment by jdmar3** [comment]
So @rvenkatraman02 and I just worked through it and made everything work for the purposes of this class. Here is what we did: 

First, we installed WSL using these instructions: https://docs.microsoft.com/en-us/windows/wsl/install#install

Open up PowerShell and run `wsl --install`. If you run this and get the WSL help in response, then that is good because WSL is already installed. If no help appears, then it will enable it and you should then restart.

Next, install a distribution. I recommend Debian (this is what I use) or Ubuntu (this is what the autograder runners use). To see what is available, run `wsl --list --online` and it will show you a list of Linux distributions you can install as your subsystem. You can install more than one if you like.

If you want to install Debian, run this: `wsl --install -d Debian` (or you can install it from the MS store: https://www.microsoft.com/en-us/p/debian/9msvkqc78pk6).

You should be prompted at some point to set a username and password. Do that.

Once that is installed, open VSCode and install the [Remote Development extension pack](https://aka.ms/vscode-remote/download/extension). This is what is going to let you access your WSL Debian from within VSCode.

In VSCode, open a folder, press F1, and select "Remote-WSL: Reopen in WSL." This _should_ make it so that you are now working in WSL instead of in Windows.

Once that is done, open a terminal, but make sure that it is a bash/Debian terminal and not a Windows/PowerShell terminal. 

At this point you should be able to see your current path by running `pwd`. Run `cd` and it will take you to your home directory for WSL. From here, we need to make sure some core utilities are installed.

Run `sudo apt update && sudo apt install curl git`. This will install cURL and git so that we can then install Node using NVM. It will ask you for a password whenever you run `apt`.

Once that install has finished, run the following: 

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`

You should see some output from that. You should then be able to run `ls -lah` and see that there is a directory `.nvm` in your home directory.

Try running `nvm list`. If nothing happens or if it gives an error, run `source .bashrc`. This will update your PATH to include the newly-installed NVM.

Once you can get some meaningful output from `nvm list` or `nvm help`, you can install the Long-Term Support version of Node by running `nvm install --lts`.

This will install Node in your WSL Debian.

And finally, you should now be able to navigate back to your previous assignment directory with `cd -`. If that doesn't take you back, then just reopen it in VSCode and you will be back in it if you open a new terminal.

Once you are in your a04 directory in a bash terminal, run `npm install` just to make sure that all of your current dependencies are installed. Then run `npm install better-sqlite3` and it should install without any issue.

ALL of this only works because we are sidestepping the Windows Node problem with build dependencies by setting up a Linux environment for development using Node. This is what I recommend, in part because you will mostly see Node running in production on UNIX environments. So, it's good to have experience working in a Linux/UNIX environment anyway. And it saves us from having to troubleshoot build dependencies on Windows, which I am not really even capable of anymore. :)

Here is a list of links for reference: 

https://docs.microsoft.com/en-us/windows/wsl/install

https://code.visualstudio.com/docs/remote/wsl

https://github.com/nvm-sh/nvm#installing-and-updating

https://github.com/JoshuaWise/better-sqlite3/blob/HEAD/docs/troubleshooting.md

https://github.com/JoshuaWise/better-sqlite3/issues/491

**Comment by mbrightman** [comment]
Thank you so much! Just got it working. So, is the idea that for the rest of the semester I should be working in this workspace instead?

**Comment by carohamunc** [comment]
Does this work for macs? When I try to use wsl --install in my terminal, I get: zsh: command not found: wsl

**Comment by elaine331917** [comment]
^ Also having trouble with installing better-sqlite3 on mac

**Comment by jdmar3** [comment]
> Does this work for macs? When I try to use wsl --install in my terminal, I get: zsh: command not found: wsl

@carohamunc  and @elaine331917 See #8 for instructions related to this.

**Comment by AstralBaby** [comment]
> So @rvenkatraman02 and I just worked through it and made everything work for the purposes of this class. Here is what we did:
> 
> First, we installed WSL using these instructions: https://docs.microsoft.com/en-us/windows/wsl/install#install
> 
> Open up PowerShell and run `wsl --install`. If you run this and get the WSL help in response, then that is good because WSL is already installed. If no help appears, then it will enable it and you should then restart.

FYI, not even switching to linux fixes this issue, its node-gyp related i think, fix your library idk, this happens in macos too.
