### ISSUE TITLE
invalid elf header sqlite-3

### ISSUE THREAD

**Issue by rkjain02** [comp426-2022-spring/a04#7]
![Screen Shot 2022-04-11 at 1 34 40 PM](https://user-images.githubusercontent.com/54414923/162797361-65a82db4-cd30-4bbf-ab57-55ef65aeca19.png)

I am running into this error. Invalid elf header on sqlite-3. I have tried looking at the documentation and different forums. I can't seem to resolve this error.

**Comment by jdmar3** [comment]
The problem turned out to be some kind of weirdness in the package-lock.json and node modules and the best way to deal with this (and a good place to start with weird errors in general) is to make sure that `node_modules` is not being pushed with your other code. If you don't have a `.gitignore` file in your repository, you should, so that git knows what is stuff that you care about and what is install or runtime cruft. 

This file is a good base `.gitignore` file for any Node package: https://raw.githubusercontent.com/github/gitignore/main/Node.gitignore 

You can put this in your repo by downloading it locally and changing the name of the file: `wget https://raw.githubusercontent.com/github/gitignore/main/Node.gitignore && mv Node.gitignore .gitignore`

You can also just copy the text at that link and put it in a new file named `.gitignore`. 

This will get rid of all of the stuff that doesn't need to be pushed to GitHub and that might get in the way of the autograder. 

Another good thing to pay attention to is what cruft your scripts are creating. In this case: `access.log` and `log.db` fit the bill because they get created at runtime but are not necessary for the program to run, even though the program accesses `log.db` occasionally. Anything that the program will create when it is run can be added to the `.gitignore` so that you don't end up distributing cruft.

Good debugging.
