### ISSUE TITLE
Unable to install better-sqlite3 on mac

### ISSUE THREAD

**Issue by carohamunc** [comp426-2022-spring/a04#8]
I've tried following the instructions for installation under the other issue about installing better-sqlite3, but I don't think it is the same for macs. When I try to use wsl --install in my terminal, I get: zsh: command not found: wsl

**Comment by jdmar3** [comment]
WSL is the "Windows Subsystem for Linux," which means that it will not be a thing on MacOS. You will want to follow the directions to install NVM, which in turn can be used to install Node.js, which will give you access to NPM, which will let you install better-sqlite3. 

Here is the documentation for NVM: https://github.com/nvm-sh/nvm#install--update-script

So, your terminal (bash) commands should look something like this: 
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
```
This will install NVM. Once it has, close your terminal and reopen it so that it knows that NVM is installed (this updates your command path and other environment variables for bash).

Then run:
```
nvm install --lts
```
This installs the Long-Term Support (LTS) version of Node (which is currently v16.14.2). You can then run:
```
nvm list
```
This shows you which versions of Node are installed on your system using NVM and whatever the system version is if it is installed system-wide as well.

Once you have the correct version of Node installed (LTS) then cd into your a04 directory, wherever that is, and run: 
```
npm install better-sqlite3
```
And NPM will add it to the `package.json` file as a dependencies and it should be installed.

**Comment by carohamunc** [comment]
Thanks so much! Had to install python and a few other things but it's working now.

**Comment by cgoldman123** [comment]
Hey guys, I'm still having some issues with downloading better-sqlite3 and I've followed all the steps here.

I'm using a Mac.
node version    v16.14.2
python version    3.8.3

Please let me know if you have any suggestions!
